### ISSUE TITLE
Migrate Othman to Python3

### ISSUE THREAD

**Issue by aelmahmoudy** [ojuba-org/othman#7]
Python 2.7 end-of-life date is on 2020: http://legacy.python.org/dev/peps/pep-0373/
Hence need to migrate Othman to Python3

**Comment by muayyad-alsadi** [comment]
as far as I know, no it does not.

**Comment by aelmahmoudy** [comment]
Ok, I started working on Python3 migration in [python3 branch] (https://github.com/ojuba-org/othman/tree/python3).

Yet, the remaining issue is the search functionality. When I use it, I get this error:
```
Traceback (most recent call last):
  File "./othman/gtkUi.py", line 265, in search_cb
    self.sw.find(b.get_text())
  File "./othman/gtkUi.py", line 95, in find
    for i in self.w.ix.findPartial(txt.split()):
  File "./othman/core.py", line 256, in findPartial
    x = reduce( lambda a,b: a|b, self.getPartial(w), searchIndexerItem() )
  File "./othman/core.py", line 236, in <lambda>
    return map(lambda i: f(i), r)
  File "./othman/core.py", line 218, in _itemFactory2
    return searchIndexerItem(a)
  File "./othman/core.py", line 166, in __init__
    set.__init__(self, *a)
  File "./othman/univaruints.py", line 179, in incremental_decode_list
    for i in a:
  File "./othman/univaruints.py", line 126, in decode
    o=ord(s[offset])
TypeError: ord() expected string of length 1, but int found
```

**Comment by khaledhosny** [comment]
This likely means that `s` (in `ord(s[offset])`) is `bytes` not `str`.

**Comment by aelmahmoudy** [comment]
I added a line in 'decode' to print 's', and I found the following:
In the original python2 code, the output was: 
```
<read-write buffer ptr 0x7fa81d5fc4f0, size 2 at 0x7fa81d5fc4b0>
```
so, the original code expects some pointer (not a string) ?

while in python3 code, the output is:
```
b'\xae]'
```
ie. bytes as @khaledhosny pointed.

**Comment by aelmahmoudy** [comment]
Python2 has reached end-of-life, please do the migration.

**Comment by aelmahmoudy** [comment]
I tried again to work on python3 (just pushed a commit yesterday), but it fails on compilation with this error:

  File "othman/univaruints.py", line 141, in encode_single
    return chr(((0b1111111100000000>>n) & 255) | ( (127>>n) & (v>>(n<<3)) )) + int64.pack(v)[8-n:]

@khaledhosny @muayyad-alsadi could you help ?

**Comment by aelmahmoudy** [comment]
I think I got it fixed now

**Comment by aelmahmoudy** [comment]
The remaining issue is in search functionality, I get this error:

Traceback (most recent call last):  File "/home/aelmahmoudy/othman/othman/gtkUi.py", line 265, in search_cb
    self.sw.find(b.get_text())
  File "/home/aelmahmoudy/othman/othman/gtkUi.py", line 95, in find
    for i in self.w.ix.findPartial(txt.split()):
  File "/home/aelmahmoudy/othman/othman/core.py", line 256, in findPartial
    x = reduce( lambda a,b: a|b, self.getPartial(w), searchIndexerItem() )
  File "/home/aelmahmoudy/othman/othman/core.py", line 233, in getPartial
    r = cn.execute('SELECT w, i FROM ix WHERE w LIKE ?', (W, ))
sqlite3.OperationalError: no such table: ix

**Comment by muayyad-alsadi** [comment]
You need to run the script that convert quranic text into sqlite database and the one that collect the reverse term index

**Comment by aelmahmoudy** [comment]
I got this error when generating index:

Traceback (most recent call last):
  File "gen-index.py", line 15, in <module>
    ix.save()
  File "/home/aelmahmoudy/othman/othman/core.py", line 206, in save
    b = univaruints.incremental_encode(self.d[w].toAyaIdList())
  File "/home/aelmahmoudy/othman/othman/univaruints.py", line 185, in incremental_encode
    return encode(incremental_encode_list(a, unique, last))
  File "/home/aelmahmoudy/othman/othman/univaruints.py", line 166, in encode
    return "".join(str(map(encode_single, a))).encode('utf-8')
  File "/home/aelmahmoudy/othman/othman/univaruints.py", line 141, in encode_single
    return chr(((0b1111111100000000>>n) & 255) | ( (127>>n) & (v>>(n<<3)) )).encode("utf-8") + int64.pack(v)[8-n:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 0: ordinal not in range(128)
make: *** [othman-data/ix.db] Error 1

**Comment by aelmahmoudy** [comment]
Nevermind the lasr post, I was running the script using python2. It works now.

**Comment by aelmahmoudy** [comment]
I still get this error when using search functionality:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/othman/gtkUi.py", line 265, in search_cb
    self.sw.find(b.get_text())
  File "/usr/lib/python3/dist-packages/othman/gtkUi.py", line 95, in find
    for i in self.w.ix.findPartial(txt.split()):
  File "/usr/lib/python3/dist-packages/othman/core.py", line 256, in findPartial
    x = reduce( lambda a,b: a|b, self.getPartial(w), searchIndexerItem() )
  File "/usr/lib/python3/dist-packages/othman/core.py", line 236, in getPartial
    return [f(i) for i in r]
  File "/usr/lib/python3/dist-packages/othman/core.py", line 236, in <listcomp>
    return [f(i) for i in r]
  File "/usr/lib/python3/dist-packages/othman/core.py", line 218, in _itemFactory2
    return searchIndexerItem(a)
  File "/usr/lib/python3/dist-packages/othman/core.py", line 166, in __init__
    set.__init__(self, *a)
  File "/usr/lib/python3/dist-packages/othman/univaruints.py", line 179, in incremental_decode_list
    for i in a:
  File "/usr/lib/python3/dist-packages/othman/univaruints.py", line 126, in decode
    o=ord(s[offset])
TypeError: ord() expected string of length 1, but int found
```

**Comment by aelmahmoudy** [comment]
I tried changing line 126 in univariants.py to:

```python
  o=ord(chr(s[offset]))
```

so I got another error on search:
```
  File "/usr/lib/python3/dist-packages/othman/gtkUi.py", line 265, in search_cb
    self.sw.find(b.get_text())
  File "/usr/lib/python3/dist-packages/othman/gtkUi.py", line 95, in find
    for i in self.w.ix.findPartial(txt.split()):
  File "/usr/lib/python3/dist-packages/othman/core.py", line 261, in findPartial
    return x.toAyaIdList()
AttributeError: 'set' object has no attribute 'toAyaIdList'
```

**Comment by aelmahmoudy** [comment]
I tried to debug this issue, I found that data type of 'x' variable in findPartial function is:

'set' in python3 version
'searchIndexerItem' in python2 version

so, I changed the return statement to:

```python
  return searchIndexerItem(x).toAyaIdList()
```

now I get this error on search:
```
  File "/usr/lib/python3/dist-packages/othman/gtkUi.py", line 265, in search_cb
    self.sw.find(b.get_text())
  File "/usr/lib/python3/dist-packages/othman/gtkUi.py", line 96, in find
    sura, aya = self.w.suraAyaFromAyaId(i)
  File "/usr/lib/python3/dist-packages/othman/core.py", line 122, in suraAyaFromAyaId
    sura = cmp_bisect_right(lambda i, j: cmp(i[3], j), self.suraInfoById, ayaId)
  File "/usr/lib/python3/dist-packages/othman/core.py", line 64, in cmp_bisect_right
    if ccmp(a[mid], x) > 0:
  File "/usr/lib/python3/dist-packages/othman/core.py", line 122, in <lambda>
    sura = cmp_bisect_right(lambda i, j: cmp(i[3], j), self.suraInfoById, ayaId)
NameError: name 'cmp' is not defined
```

**Comment by muayyad-alsadi** [comment]
please verify that this is fixed.

https://github.com/ojuba-org/othman/pull/17

**Comment by aelmahmoudy** [comment]
الحمد لله

I was able to test today using latest commit in master, and it works.
